In [2]:
pip install tensorflow

In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.11.0'

In [5]:
tf.keras.__version__

'2.11.0'

## GPU/CPU check 

In [8]:
variable=tf.Variable([3,3])
if tf.test.is_gpu_available():
    print("GPU")
    print(var.device.endswith('GPU:0'))
else:
    print("CPU")

CPU


In [12]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>

## Tensor constant 

In [11]:
ineuron=tf.constant(34)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=34>

In [13]:
ineuron.numpy()

34

In [14]:
ineuron1=tf.constant(1,dtype=tf.int64)#Changing the datatype
ineuron1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [18]:
ineuronx=tf.constant([[4,2],[9,5]])
ineuronx

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]])>

## tf.ones and tf.zeros linke np.ones,np.zeros 

In [19]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [21]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [22]:
a=tf.constant([[3,4,5],[3,4,5]])
b=tf.constant([[1,2,3],[4,5,6]])
c=tf.add(a,b)
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [ 7,  9, 11]])>

## Random Constant

In [23]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2231616 ,  1.1473863 ],
       [-0.41847336, -0.66458553]], dtype=float32)>

In [24]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [1, 4]])>

## Declaring Variables 

In [25]:
var0=24#Python variable
var1=tf.Variable(42)# Rank0 tensor
var2=tf.Variable([[0,1,2],[3,4,5],[6,6,7]])# Rank 3 tensor
var0,var1,var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 6, 7]])>)

#### To reassign a variable,use var.assign() 

In [27]:
var_reassign=tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [28]:
var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [30]:
init=tf.random.normal(shape=(2,2))
a=tf.Variable(init)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-3.239043  , -0.01517784],
       [ 0.7367106 , -1.266162  ]], dtype=float32)>


### We can assign ==,+=,-= values 

In [39]:
new_val=tf.random.normal(shape=(2,2))
a.assign(new_val)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_val[i,j]

In [40]:
added_val=tf.random.normal(shape=(2,2))
a.assign_add(added_val)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_val[i,j] + added_val[i,j]

### Shaping the tensor 

In [44]:
tensor=tf.Variable([[[10,11,12],[3,4,5],[45,6,7]]])
tensor.shape

TensorShape([1, 3, 3])

### Tensors can be reshaped and retain the same values which is required for constructing Neural networks 

In [48]:
tf.reshape(tensor,[1,9])#- will not work 

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[10, 11, 12,  3,  4,  5, 45,  6,  7]])>

### Rank of a tensor 

Rank of a tensor is defined as a number of dimension,which is the number of indices that are required to specify any particular element of the tensor

In [49]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### Casting tensor to a numpy 

In [59]:
type(tensor.numpy())

numpy.ndarray

In [ ]:
#np-magnitude
#tf-magnitude,direction,--- in which it helps to compute neurons,graphical

### Transpose Matrix Multiplication 

In [60]:
u=tf.constant([[6,7,8]])
v=tf.constant([[3,4,5]])
tf.matmul(u,tf.transpose(v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[86]])>

### Casting a tensor to another datatype 

In [61]:
i=tf.cast(tensor,dtype=tf.int32)
i

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [ 3,  4,  5],
        [45,  6,  7]]])>

### Calculate the mean 

In [62]:
n=tf.constant([[8,9],[1,2]])
tf.reduce_mean(input_tensor=n)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [63]:
tf.reduce_mean(input_tensor=n,axis=0)# Mean across rows if columns then axis=1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5])>

In [64]:
tf.reduce_mean(input_tensor=n,axis=0,keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 5]])>